/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.Geometry;
using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.Rob8
{
    public class Boxes : Message
    {
        public override string RosMessageName => "rob8/Boxes";

        public long boxid { get; set; }
        public Pose pose { get; set; }
        public String type { get; set; }
        public float scalex { get; set; }
        public float scaley { get; set; }
        public float scalez { get; set; }

        public Boxes()
        {
            this.boxid = 0;
            this.pose = new Pose();
            this.type = new String();
            this.scalex = 0.0f;
            this.scaley = 0.0f;
            this.scalez = 0.0f;
        }

        public Boxes(long boxid, Pose pose, String type, float scalex, float scaley, float scalez)
        {
            this.boxid = boxid;
            this.pose = pose;
            this.type = type;
            this.scalex = scalex;
            this.scaley = scaley;
            this.scalez = scalez;
        }
    }
}
