# Define the goal
bool runpath  #Define if we should execute or recalculate
---
# Define the result
bool succededTrue #Returns true if robot finished the paths
---
# Define a feedback message
uint32 currentPath #Which path we're currently on